openapi: 3.0.0
info:
  title: Bag Index Service API
  version: 1.2.3
  description: |
    This document specifies the Bag Index Service API. It provides relational metadata about items in the bag stores.
    This API implements the operations `GET` on the paths `/`, `/bag-sequence?contains=:UUID`, `/search?doi=:DOI` and `/bags/:UUID` and implements the operation PUT on `/bags/:UUID`
    It is not neccessary for this service to supply the bag store the bag is stored in.

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0

servers:
  - url: 'http://localhost:20120'
    description: Local machine running Bag Index

paths:
  /:
    get:
      summary: Returns a description of the service.
      description:
        This is the starting place for navigating the Bag Index Service. It returns a description of the service.
      responses:
        200:
          description: Description of the service
          content:
            text/plain:
              schema:
                type: string
                description: A plain text, human readable description of the service
                example: EASY Bag Index running v1.2.3

  /search?doi={DOI}:
    get:
      summary: Returns the Bag Index metadata for all items related to a digital object identifier.
      description: |
        The item fetched is specified by the DOI. The results can contain more than one bag-info object.

      parameters:
        - $ref: '#/components/parameters/DOI'

      responses:
        200:
          description: Bag index object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bagIndexArrayOk"
            application/xml:
              schema:
                $ref: "#/components/schemas/bagIndexArrayOk"
        400:
          description: The query parameter was not supported.
        500:
          $ref: '#/components/responses/Unavailable'

  /bag-sequence?contains={UUID}:
    get:
      summary: Returns a newline separated list of UUIDs that make up the bag-sequence for the specified bag.
      description: |
        The fetched list is specified by the item-id of any bag in the sequence. The items are listed in order of their creation date. If the UUID is not found an empty list is returned.
      parameters:
        - $ref: '#/components/parameters/UUID'

      responses:
        200:
          description: Newline separated list of UUIDs
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bagSequenceOk"
            application/xml:
              schema:
                $ref: "#/components/schemas/bagSequenceOk"
        400:
          description: The UUID was syntactically incorrect.
        500:
          $ref: '#/components/responses/Unavailable'

  /bags/{UUID}:
    get:
      summary: Returns the Bag Index metadata for a bag with the specified item-id.
      description: |
        The Bag Index metadata related to a single bag are retrieved from the index.

      parameters:
        - $ref: '#/components/parameters/UUID'

      responses:
        200:
          description: Bag index object
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/bagIndexOk"
            application/xml:
              schema:
                $ref: "#/components/schemas/bagIndexOk"
        400:
          description: The UUID was syntactically incorrect.
        404:
          description: Bag-index metadata could not be found for the specified item-id.
        500:
          $ref: '#/components/responses/Unavailable'
    put:
      summary: Adds the Bag Index metadata of a single bag to the index.
      description: |
        The bag for which the metadata should be added to the index is specified by the item-id.
      parameters:
        - $ref: '#/components/parameters/UUID'

      responses:
        201:
          description: The object has been created.
        400:
          description: |
            the request was rejected by the bag-index. The reason will be included in the response entity. Some possible causes are:

            * The bag has already been added to the index.
            * The UUID was syntactically incorrect.
            * The bag could not read, and may have been corrupt.
            * The DOI could not be found in the bag's metadata.
            * Bag-info.txt contains an invalid Is-Version-Of identifier tag.
        404:
          A bag with the specified item-id could not be found.
        500:
          $ref: '#/components/responses/Unavailable'


components:
  parameters:
    UUID:
      in: path
      name: UUID
      schema:
        type: string
      required: true
      description: bag-id of the targeted bag
    DOI:
      in: path
      name: DOI
      schema:
        type: string
      required: true
      description: digital object identifier of the targeted bag

  responses:
    Unavailable:
      description: Service is unavailable because of an error.
    FileNotFound:
      description: The item could not be found.

  schemas:
    bagIndexOk:
      type: object
      example:
        result:
          bag-info:
            bag-id: 40594b6d-8378-4260-b96b-13b57beadf7c,
            base-id: 40594b6d-8378-4260-b96b-13b57beadf7c,
            created: 2015-05-19T00:00:00.000+02:00,
            doi: 10.17026/test-x6f-kf66
      properties:
        result:
          type: object
          properties:
            bag-info:
              type: object
              properties:
                bag-id:
                  type: string
                  format: "uuid"
                base-id:
                  type: string
                  format: "uuid"
                created:
                  type: string
                  format: "date-time"
                doi:
                  type: string
                  format: "doi"

    bagIndexArrayOk:
      type: object
      example:
        result:
          - bag-info:
              bag-id: 40594b6d-8378-4260-b96b-13b57beadf7c,
              base-id: 40594b6d-8378-4260-b96b-13b57beadf7c,
              created: 2015-05-19T00:00:00.000+02:00,
              doi: 10.17026/test-x6f-kf66
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              bag-info:
                properties:
                  bag-id:
                    type: string
                    format: "uuid"
                  base-id:
                    type: string
                    format: "uuid"
                  created:
                    type: string
                    format: "date-time"
                  doi:
                    type: string
                    format: "doi"

    bagSequenceOk:
      type: string
      example:
        c01d7876-8080-4597-81fe-9083b5463cc1\n a165d874-b8b1-4870-94dc-3242a6a44ab8\n ef5d6285-c835-4199-9ae8-72cf9407b81c
